# Configuración de build para Netlify
[build]
  publish = "dist"
  command = "npm run build"
  base = "/"
  functions = "netlify/functions"

# Configuración de despliegue para la rama principal
[context.production]
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

# Configuración de despliegue para desarrollo
[context.deploy-preview]
  command = "npm run build:dev"
  environment = { NODE_VERSION = "18" }

# Forzar siempre la limpieza del caché para los nuevos despliegues
[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_FORCE_CLEAR_CACHE = "true"
  NODE_VERSION = "18"
  # Variables para OAuth de Facebook/Instagram
  FACEBOOK_APP_ID = "925270751978648"
  INSTAGRAM_REDIRECT_URI = "https://kalma-lab.netlify.app/.netlify/functions/instagram-callback"
  # IMPORTANTE: Debes configurar estos valores en el panel de Netlify
  # Las siguientes variables DEBEN configurarse en el panel de Netlify:
  # - GOOGLE_CLIENT_ID: ID del cliente OAuth de Google
  # - GOOGLE_CLIENT_SECRET: Secreto del cliente OAuth de Google 
  # - URL_GOOGLE: URL base de Kalma (p.ej. https://kalma-lab.netlify.app)
  # - FACEBOOK_APP_SECRET: Secreto de la aplicación de Facebook
  # Son secretos y no deben estar en el archivo de configuración
  NETLIFY_SKIP_TOML_VALIDATION = "1"

# Configuración de redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/instagram/callback"
  to = "/.netlify/functions/instagram-callback"
  status = 200

[[redirects]]
  from = "/auth/gmail/callback"
  to = "/.netlify/functions/gmail-callback"
  status = 200 