# Configuración de build para Netlify
[build]
  publish = "dist"
  command = "npm run build"
  base = "/"

# Configuración de despliegue para la rama principal
[context.production]
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

# Configuración de despliegue para desarrollo
[context.deploy-preview]
  command = "npm run build:dev"
  environment = { NODE_VERSION = "18" }

# Forzar siempre la limpieza del caché para los nuevos despliegues
[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_FORCE_CLEAR_CACHE = "true"
  NODE_VERSION = "18"
  # Variables para OAuth de Facebook/Instagram
  FACEBOOK_APP_ID = "925270751978648"
  INSTAGRAM_REDIRECT_URI = "https://kalma-lab.netlify.app/.netlify/functions/instagram-callback"
  # IMPORTANTE: Debes configurar estos valores en el panel de Netlify
  # FACEBOOK_APP_SECRET debe configurarse como variable de entorno en Netlify
  # Son secretos y no deben estar en el archivo de configuración

# Configuración de redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 